// Activity Log Enums - shared across modules

export enum ActivityAction {
  MEMBER_INVITED = 'member_invited',
  MEMBER_INVITE_ACCEPTED = 'member_invite_accepted',
  MEMBER_ROLE_CHANGED = 'member_role_changed',
  MEMBER_REMOVED = 'member_removed',
  CONTENT_CREATED = 'content_created',
  CONTENT_UPDATED = 'content_updated',
  CONTENT_PUBLISHED = 'content_published',
  CONTENT_DELETED = 'content_deleted',
  CONTENT_CANCELLED = 'content_cancelled',
  SOCIAL_ACCOUNT_CONNECTED = 'social_account_connected',
  SOCIAL_ACCOUNT_DISCONNECTED = 'social_account_disconnected',
  AI_ADAPTATION_RUN = 'ai_adaptation_run',
  COMPLIANCE_SCAN_RUN = 'compliance_scan_run',
  COMPLIANCE_OVERRIDE = 'compliance_override',
  EXPORT_DATA_REQUESTED = 'export_data_requested',
  DATA_DELETION_REQUESTED = 'data_deletion_requested',
}

export enum AuditAction {
  USER_CREATED = 'user_created',
  USER_UPDATED = 'user_updated',
  USER_DELETED = 'user_deleted',
  WORKSPACE_CREATED = 'workspace_created',
  WORKSPACE_UPDATED = 'workspace_updated',
  WORKSPACE_DELETED = 'workspace_deleted',
  MEMBER_INVITED = 'member_invited',
  MEMBER_ROLE_CHANGED = 'member_role_changed',
  MEMBER_REMOVED = 'member_removed',
  SOCIAL_ACCOUNT_CONNECTED = 'social_account_connected',
  SOCIAL_ACCOUNT_DISCONNECTED = 'social_account_disconnected',
  SOCIAL_ACCOUNT_TOKEN_REFRESHED = 'social_account_token_refreshed',
  CONTENT_CREATED = 'content_created',
  CONTENT_UPDATED = 'content_updated',
  CONTENT_DELETED = 'content_deleted',
  CONTENT_PUBLISHED = 'content_published',
  AI_ADAPTATION_RUN = 'ai_adaptation_run',
  COMPLIANCE_SCAN_RUN = 'compliance_scan_run',
  COMPLIANCE_OVERRIDE = 'compliance_override',
  API_KEY_CREATED = 'api_key_created',
  API_KEY_REVOKED = 'api_key_revoked',
  WEBHOOK_CREATED = 'webhook_created',
  WEBHOOK_UPDATED = 'webhook_updated',
  WEBHOOK_DELETED = 'webhook_deleted',
  SYSTEM_CONFIG_CHANGED = 'system_config_changed',
  EXPORT_DATA_REQUESTED = 'export_data_requested',
  DATA_DELETION_REQUESTED = 'data_deletion_requested',
}

export enum AuditResource {
  USER = 'user',
  WORKSPACE = 'workspace',
  MEMBER = 'member',
  SOCIAL_ACCOUNT = 'social_account',
  CONTENT = 'content',
  AI_ADAPTATION = 'ai_adaptation',
  COMPLIANCE_SCAN = 'compliance_scan',
  API_KEY = 'api_key',
  WEBHOOK = 'webhook',
  SYSTEM = 'system',
}
